### ISSUE TITLE
CPU compatibility

### ISSUE THREAD

**Issue by XinhuiLi** [denbonte/CER3BRUM#1]
Hi,

I read your paper earlier this year and I am excited to see that the code is finally available! Great work! 

The notebook is very clear but I got an error message when I tried to run training.ipynb on my local CPU: 
`RuntimeError: /job:localhost/replica:0/task:0/device:GPU:0 unknown device.`

Does current notebook support CPU? If so, how could I modify the code to make it run on CPU? Thanks so much for your help!

**Comment by denbonte** [comment]
Dear Xinhui,

> I read your paper earlier this year and I am excited to see that the code is finally available! Great work!

Thank you so much for the kind words!

> The notebook is very clear 

Glad to hear that.

> but I got an error message when I tried to run training.ipynb on my local CPU:
> `RuntimeError: /job:localhost/replica:0/task:0/device:GPU:0 unknown device.`

The reason why the error was raised is that the code I put on GitHub is exactly the one we used to train the model that made into the paper - i.e., distributing the former on NVIDIA 4x1080Ti.

If you open `cer3brum_lib/fullyvol/cer3brum.py` you'll see what I mean: the different parts of the architecture are conveniently placed on different GPUs by using `with tf.device('/gpu:0'):` before instantiating the custom blocks (found in `cer3brum_lib/fullyvol/cer3blocks.py`).

> Does current notebook support CPU? If so, how could I modify the code to make it run on CPU? Thanks so much for your help!

The shortcoming of training such fully-volumetric models (as with, for instance, GANs) is that they require a lot of VRAM (or some other tricks like mixed precision - that unfortunately wasn't really well developed when we started working on the project, mid-2018). Therefore, although it could be done in principle (of course under the hypothesis you have a lot of RAM on that machine), it would turn out to be painfully slow!

If you'd still like to try, just get rid of all the `with tf.device('/gpu:*'):` in the script that creates the graph.

**Comment by XinhuiLi** [comment]
Hi Dennis,

Thank you so much for your prompt reply. Yeah the script works after I comment out `with tf.device('/gpu:*'):` but I run into the same issue as https://github.com/denbonte/CER3BRUM/issues/2 on local though I install packages with exactly same version as you suggested. I'll dig into it and let you know how it goes.

Truly appreciate your help.

Thanks,
Xinhui
